### ISSUE TITLE
HttpServletRequest.getRequestUrl is incorrect

### ISSUE THREAD

**Issue by mattcorey** [awslabs/aws-serverless-java-container#10]
When running in AWS using the Spring integration, fronted by an API Gateway in AWS Proxy mode, calling HttpServletRequest returns a StringBuffer of the following format:

`<api-gateway-host>//<requestPath>`

It _should_ return something like the following:

`<scheme>://<api-gateway-host>/<stage>/<requestPath>`

The primary visible impact of this is when using the Spring Data REST with auto-generated Controllers from Repositories - this creates HATEAOS-based Entities with self references, however all of the references are wrong.  The ALPS metadata at the 'profile' endpoints are all incorrect as well.

**Comment by SAPessi** [comment]
Thanks Matt, will review and give feedback/merge tomorrow. Keep the feedback coming if you run into any other issue and we'll make the fix.

**Comment by SAPessi** [comment]
I've merged the pull request, closing this issue.

**Comment by mancini0** [comment]
I am running into a similar issue using aws-serverless-java-container-spring 1.0, Spring-HATEOS 0.24,  and Spring Boot 2.0.  It is not a big deal for me since a workaround is mapping the a custom domain name to the  combined base url and stage, but I wonder if this ticket should be re-opened.


![image](https://user-images.githubusercontent.com/5806901/37739190-69c3c696-2d27-11e8-9652-2539947ccc5b.png)

**Comment by SAPessi** [comment]
@mancini0 you can configure the library to include the stage as part of the request url/context path. See [`AwsProxyHttpServletRequest`](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequest.java#L209).

The configuration is a singleton you can grab from the handler class:
```java
LambdaContainerHandler.getContainerConfig().setUseStageAsServletContext(true);
```
