### ISSUE TITLE
Spring - webRequest.checkNotModified(...) not working

### ISSUE THREAD

**Issue by andregrund** [awslabs/aws-serverless-java-container#122]
* Framework version: 0.9.1
* Implementations: Spring

## Scenario
I want to use HTTP 1.1 header "If-Modified-Since". When sending a request with that header "If-Unmodified-Since" is checked first, see `org.springframework.web.context.request.ServletWebRequest#checkNotModified(String s, long l)`. This calls `com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequest#getDateHeader(String s)`. If the header is not set (null), a `new Date().getTime()` is returned which I think is not correct.
## Expected behavior
As stated in the documentation I expect a _304_ HTTP status code when using `webRequest.checkNotModified(long l)` and no modification has been made. To archive this, `getDateHeader(String s)` should return _-1L_ in case a header has not been set.
## Actual behavior
`org.springframework.web.context.request.ServletWerRequest#validateIfUnmodifiedSince(long l)` expects _-1L_ in case no modification has been made. This should also be returned if no header has been set at all.

**Comment by SAPessi** [comment]
Thanks for the feedback @andregrund, I'll try to replicate and get back to you early next week.

**Comment by SAPessi** [comment]
Hey @andregrund, this was indeed a bug. I've addressed in the latest commit on the `core` branch and also took the opportunity to move to the faster time package rather than the old `SimpleDateFormat`. The fix will go out with the 1.0 release in a week or two. If you want to test now, you can use the core branch in local now:

```bash
$ git clone https://github.com/awslabs/aws-serverless-java-container.git
$ cd aws-serverless-java-container
$ git checkout core
$ git pull # just in case

$ mvn install
```

Once you have installed the library, just change your pom file to use version `1.0-SNAPSHOT`. Maven will resolve that in local automatically.

**Comment by andregrund** [comment]
Hello @SAPessi . Thank you for the fix. I just tested it and it workes like a charm. Looking forward to the 1.0 release.

**Comment by SAPessi** [comment]
Thanks for confirming. I'll close this issue.
