### ISSUE TITLE
Block build on code coverage

### ISSUE THREAD

**Issue by sapessi** [awslabs/aws-serverless-java-container#160]
Include [Jacoco](https://www.jacoco.org/jacoco/) plugin in the build process and block build unless code coverage is > 70%.

**Comment by SAPessi** [comment]
Currently set the coverage requirements to 50%. All implementations are above 70%. However, code coverage on the core package is a little over 50%. While our target is 70%, we also need to release 1.2 sooner rather than later since it includes important bug fixes and new features. We'll keep chipping away at this for the next release and hopefully hit 70% in 1.3.
