### ISSUE TITLE
How to setup a test cases for Spring boot

### ISSUE THREAD

**Issue by dotekien** [awslabs/aws-serverless-java-container#180]
* Framework version: latest
* Implementations: Spring Boot

## Scenario
I want to write a controller test cases but unable to invoke the spring application

**Comment by SAPessi** [comment]
Hey @dotekien, if you used the archetypes from the [quick start guides](https://github.com/awslabs/aws-serverless-java-container/wiki/Quick-start---Spring-Boot) they come with 1 test case you can re-use. Otherwise, you could look at our [existing tests for Spring Boot](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/SpringBootAppTest.java#L29).

**Comment by dotekien** [comment]
Thanks.
