### ISSUE TITLE
KPL with Lambda

### ISSUE THREAD

**Issue by vijaychd** [awslabs/aws-serverless-java-container#207]
* Framework version: 1.2
* Implementations: Spring Boot

## Scenario
Use KPL for logging from lambda function

## Expected behavior
Lambda to wait for KPL to complete the processing.

## Actual behavior
KPL write are getting terminated after handler returns.

**Comment by SAPessi** [comment]
Hi @vijaychd, this is indeed the expected behavior. Lambda will freeze the execution environment as soon as your handler returns, we have no control over this behavior.

My recommendation is normally to use the default logging mechanism to CloudWatch Logs, then configure CloudWatch to [stream the logs to a Lambda function](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/SubscriptionFilters.html#LambdaFunctionExample) that takes care of the export to a 3rd party system.

**Comment by vijaychd** [comment]
@SAPessi Thanks.  Is Streaming logs to Cloudwatch Synchronous so that it is guaranteed?

**Comment by SAPessi** [comment]
Yes. Lambda takes care of sending your stdout to cloudwatch so that you don't have to worry about it. There's also a [custom appender for log4j](https://docs.aws.amazon.com/lambda/latest/dg/java-logging.html)

**Comment by vijaychd** [comment]
So why cant i use custom appender which uses Kinesis behind the scenes.

**Comment by SAPessi** [comment]
Because you'd have to send the records to kinesis yourself. This means you'd have to do it synchronously during the execution of the handler, adding latency, to make sure all log records are sent. The native Lambda logging mechanism takes care of doing that behind the scenes asynchronously.

**Comment by SAPessi** [comment]
Absolutely! I'll take this to the lambda team!
