### ISSUE TITLE
Invoke custom servlet filter before JerseyFilter?

### ISSUE THREAD

**Issue by martinpllu** [awslabs/aws-serverless-java-container#209]
I'm using the Jersey implementation and I am registering `javax.servlet.Filter` instances as described [in the wiki](https://github.com/awslabs/aws-serverless-java-container/wiki#servlet-filters). 

I would like my filters to be invoked before the API resource methods, e.g. to validate security credentials. However when I register filters in this way, they are invoked after the resource methods.

As far as I can see there is no way to control this; the JerseyFilter is registered in `com.amazonaws.serverless.proxy.jersey.JerseyLambdaContainerHandler.initialize()` before `com.amazonaws.serverless.proxy.internal.servlet.AwsLambdaServletContainerHandler.onStartup()` is called. I can't see any obvious way to modify the filter ordering.

I'm considering building a mechanism to allow custom filters to be registered before JerseyFilter. I just wanted to check that I'm not missing something, and that this sounds like a reasonable thing to do.

**Comment by martinpllu** [comment]
Thanks @sapessi. For context I have a fairly large set of legacy filters that depend heavily on the HttpServletRequest/Response APIs.

I had tried using JAX-RS filters and while they do solve the filter ordering problem, I am unable to inject HttpServletRequest/Response objects into the filter. 

See (https://github.com/martinpllu/my-service)[https://github.com/martinpllu/my-service] which demonstrates a simple JAX-RS filter with an injected request:

```
public class MyJaxRsFilter implements ContainerRequestFilter {
	
	@Context HttpServletRequest request;

	public void filter(ContainerRequestContext ctx) throws IOException {
		
    	System.out.println("Hello JAXRS filter, request = " + request);
	}

}
```

When I run `StreamLambdaHandlerTest` I get `java.lang.IllegalStateException: Not inside a request scope`

If I run the same code inside another Jersey implementation, e.g. RestEasy on Jetty, the request object is successfully injected.

Is this perhaps a bug in the Jersey implementation?

**Comment by sapessi** [comment]
Understood, thanks @martinpllu. The best work-around I can think of is to use the constructor for [`JerseyLambdaContainerHandler`](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-jersey/src/main/java/com/amazonaws/serverless/proxy/jersey/JerseyLambdaContainerHandler.java) instead of the static `getAwsProxyHandler` method. This way you can:

1. Construct a new `JerseyLambdaContainerHandler` with the same parameters that [the static method uses](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-jersey/src/main/java/com/amazonaws/serverless/proxy/jersey/JerseyLambdaContainerHandler.java#L98)
2. Register your own filters in the servlet context (`getServletContext()` on the object)
3. Call the [`initialize()` method](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-jersey/src/main/java/com/amazonaws/serverless/proxy/jersey/JerseyLambdaContainerHandler.java#L177) manually so that the jersey filter will be the last one registered.

**Comment by sapessi** [comment]
I'll try and replicate your second issue - not being able to inject the servlet request in a filter - and open a separate issue to track it as a bug.

**Comment by martinpllu** [comment]
Thanks @sapessi, your suggested work-around does the job nicely. I'll be interested to see if you can replicate the ContainerRequestFilter servlet injection problem; feel free to close this issue in any case. Thanks again, much appreciated.

**Comment by sapessi** [comment]
Resolving this issue. I've created #211 to track the injection issue

**Comment by jamietanna** [comment]
For anyone looking at this in the future, I've documented this in a little more depth [on my blog](https://www.jvt.me/posts/2021/01/25/servlet-filter-jersey-aws-serverless/) and have an example project [on GitLab](https://gitlab.com/jamietanna/jersey-servlet-filter-example) - thanks for pointing me in the right direction!

(Originally published at: https://www.jvt.me/mf2/2021/01/b4lwl/)
