### ISSUE TITLE
@RequestParam("file") MultipartFile input - byte size seems to double when running via a lambda

### ISSUE THREAD

**Issue by peavers** [awslabs/aws-serverless-java-container#235]
* Framework version: 1.3
* Implementations: Spring Boot

## Scenario
Running locally, the byte size of a `MultipartFile` is correct, running via Lambda the file size is approximately twice as big, and is no longer a valid file. 

## Expected behavior
`input.getBytes()` will return the same number of bytes when running in a Lambda as it does locally

## Actual behavior
`input.getBytes()` returns double the number of bytes expected

## Steps to reproduce
A simple controller
```java

@RestController
public class Controller {

    @PostMapping("/sample")
    public void sample(@RequestParam("file") MultipartFile input) throws IOException {
        log.info("input size {}", input.getBytes());
    }
}
```

Using the `StreamLambdaHandler` from the example. 

```java
public class StreamLambdaHandler implements RequestStreamHandler {
    private static SpringBootLambdaContainerHandler<AwsProxyRequest, AwsProxyResponse> handler;

    static {
        try {
            handler = SpringBootLambdaContainerHandler.getAwsProxyHandler(Application.class);
        } catch (ContainerInitializationException e) {
            e.printStackTrace();
            throw new RuntimeException("Could not initialize Spring Boot application", e);
        }
    }

    @Override
    public void handleRequest(InputStream inputStream, OutputStream outputStream, Context context)
            throws IOException {
        handler.proxyStream(inputStream, outputStream, context);
    }
}
```
The real problem here is when attempting to use the input in something like `Rekognition` I'm getting
```
com.amazonaws.services.rekognition.model.InvalidImageFormatException: Request has invalid image format (Service: AmazonRekognition; Status Code: 400; Error Code: InvalidImageFormatException; Request ID: 315327a5-29a0-11e9-be55-dde1f05f2a30)
```
But works perfect when running locally. I assume this has something to do with the Proxy, but would love some help/guidance in how to solve this as it's a pretty major blocker at the moment for me. 

Really hoping I've just not setup something properly, or I'm not handling the incoming request properly? 

Cheers,

**Comment by sapessi** [comment]
Hi @peavers, I suspect this is because the `Content-Type` is not treated as binary. First, you need to configure API Gateway to handle requests with a content type of `multipart/form-data` (I assume) as binary - you can find the guide [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings-configure-with-console.html). Because Lambda does not support binary events, API Gateway automatically base64-encodes the request body to pass it to the Lambda handler. 

You can then configure this framework to recognize binary contents by setting the `ContainerConfig` property as documented [here](https://github.com/awslabs/aws-serverless-java-container/wiki#container-configuration) with the `addBinaryContentTypes(String...)`  method.

**Comment by peavers** [comment]
You're correct my friend that was it. Simply adding `multipart/form-data` was enough to get things working as expected. Much appreciated.
