### ISSUE TITLE
JDBC Connection Pools - Recommendation for Lambda runtime

### ISSUE THREAD

**Issue by vijaychd** [awslabs/aws-serverless-java-container#238]
* Framework version: 1.3
* Implementations: Spring Boot

## Scenario
How to ensure database connection pools are managed effectively when running in Lambda.  Any recommendations?

**Comment by sapessi** [comment]
Hi @vijaychd, Lambda itself enforces that each function instance only processes one event at a time. For this reason, your connection pool should have a max size of 1. Make sure you declare the connection pool as a singleton so that it can be re-used for all subsequent invocations of the function. Finally, if you are running against a database that cannot handle large number of connections, make sure that you set a concurrency limit on the Lambda function to the maximum number of connections that your database can handle - otherwise you risk taking everything down as Lambda scales up for you.

**Comment by sapessi** [comment]
Assuming the answer was accepted. Closing this issue.

**Comment by vijaychd** [comment]
yes.  thanks

**Comment by davidmco65** [comment]
Hi, I have a different experience.   We use C3P0 for connection pooling (Java) but when we see the UnknownHostException issue in Lambdas, it's good that we set our max connection pool size to 2 or 3.  So sometimes one of the connections will go stale and can't reconnect but the process has another connection to use.  Just my .02 worth.
Mac
