### ISSUE TITLE
Streaming AWS Proxy servlet Response

### ISSUE THREAD

**Issue by sunnypav** [awslabs/aws-serverless-java-container#321]
* Framework version: XX
* Implementations: Jersey / Spring / Spring Boot / Spark

## Scenario
I am using just the serverless-java-container-core project and one of the issue i want to bring is currently the response getting stored in memory there by if many requests come at once the heap memory of the lambda is shooting up is there any way we can stream the response instead of storing it in bytearrayoutputstream (in awsproxyservletresponse.java)

**Comment by sapessi** [comment]
Lambda does not support streaming or requests and responses. We need to return the entire object at once. However, I would not be concerned about memory consumption since the Lambda service itself will enforce that each sandbox - and therefore instance of this library - only handles one request at a time. If you receive a spike of traffic, Lambda will spawn more sandboxes, it will not send additional requests to a sandbox that is already busy processing one event.
