### ISSUE TITLE
[Question] Connection close by using Hikari Datasource 

### ISSUE THREAD

**Issue by forest6511** [awslabs/aws-serverless-java-container#324]
* Implementations: Spring Boot2

## Scenario
Cloudwatch -> Lambda -> Aurora(Postgres)

### Expected behavior
When Lambda timeout,  JDBC connection pool is cleanup or rather all connection close.

Im considering to implement  Spring Boot2 with spring jdbc, HikariDatasouce and this serverless framework.
I wonder when aws Lambda timeouts,  Hikari Datasource connections pool are cleanup?

**Comment by sapessi** [comment]
Hi @forest6511, at the moment there is no safe way to handle that case in Lambda since your application does not receive notifications of the sandbox being shutdown/recycled. Further, in-between invocations - as soon as you return from the handler method - the sandbox and your code are frozen. To interact with relational databases I'd recommend connecting to the [RDS proxy](https://aws.amazon.com/blogs/compute/using-amazon-rds-proxy-with-aws-lambda/) and not deal with connection management on your side at all.

**Comment by forest6511** [comment]
I understand. 
Considering Lambda's timeouts, I will check RDS proxy(Aurora MySQL) as db pool and I need to design to prevent  Lambda app from timeout.
 
Thank you.
Please close this issue.
