### ISSUE TITLE
@PathVariables not URL encoded 

### ISSUE THREAD

**Issue by eranation** [awslabs/aws-serverless-java-container#53]
In a classic Spring deployment (e.g. on a standalone / built in Spring Boot embedded Tomcat), when you get a @PathVariable, usually it's already URL decoded, e.g. if I send a request to 

/foo/bar/Some%20Thing 

to a 

@GetMapping("/foo/bar/{baz}")
public void handle(@PathVariable("baz") String baz) … 

then baz should be "Some Thing"  

This can be fixed in the Lambda handler easily, but I think it will be nice the container will take care of it (can be a configuration param as it's a breaking change) 

Right now the workaround I used is simply: 

request.setPath(java.net.URLDecoder.decode(request.getPath(), "UTF-8"));

**Comment by SAPessi** [comment]
Since we are not yet at version 1.0, I think we can afford a breaking change. This clearly looks like a bug so I'd be in favor of simply changing the behavior of the library. I will ask the community in the Gitter chat for feedback and do some research - I'll update this issue next week.

**Comment by SAPessi** [comment]
hey @eranation, I did some research on this and it turns out containers do automatically URIDecode a request with the configured charset. Spring Boot automatically configures this to UTF-8: https://dddpaul.github.io/blog/2015/12/21/spring-boot-uri-encoding/

I will add a new `uriEncoding` parameter to the [`ContainerConfig`](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/model/ContainerConfig.java) and set the default to UTF-8. If you need to modify the encoding, you can retrieve the config from the [handler object](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/LambdaContainerHandler.java#L147) and change the value.

**Comment by SAPessi** [comment]
I've pushed a fix for this to the `servlet-improvements` branch. If you get a chance to test the latest version from that branch let me know if this works for you. I've added a couple of unit tests to the spring implementation and the core request reader.

**Comment by SAPessi** [comment]
This was reported as fixed offline. Closing the issue.
