### ISSUE TITLE
ApiGatewayAuthorizerContext not serializing contextProperties

### ISSUE THREAD

**Issue by iannickb** [awslabs/aws-serverless-java-container#69]
We are adding some context in a custom authorizer and it seems like the ApiGatewayAuthorizerContext is not serializing it properly. The principalId is available but we can't get anything else through `getContextValue(String key)`.

Everything also works fine when using the following interface:
```
public AwsProxyResponse handleRequest(Map<String, Object> input, Context context) {}
```

**Comment by SAPessi** [comment]
This is probably because the model objects [use annotations](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/model/ApiGatewayAuthorizerContext.java#L52) to serialize the event correctly. The default Lambda serializer does not support annotations. The only way to work around this is to use your own ObjectMapper instance and the Lambda stream handler. Take a look at [this Spring sample](https://github.com/awslabs/aws-serverless-java-container/blob/master/samples/spring/pet-store/src/main/java/com/amazonaws/serverless/sample/spring/StreamLambdaHandler.java#L26).

**Comment by iannickb** [comment]
This is exactly the workaround I have, thanks @SAPessi.
