### ISSUE TITLE
enable cors in container

### ISSUE THREAD

**Issue by cenxui** [awslabs/aws-serverless-java-container#74]
It is possible to modify sam.yaml to enable cors without adding swagger.yaml or manually enable cors in APIGateway? If not how to dynamically add the lambda function name to swagger. The lambda function  will be FUNCTION_NAME-XXXXXXX "XXXXXX" is random hash.

**Comment by SAPessi** [comment]
At the moment this is not possible - the SAM team has taken on a feature request for this and they will work on it: https://github.com/awslabs/serverless-application-model/issues/23

**Comment by SAPessi** [comment]
Closing this as should be handled by the SAM team.

**Comment by m1ky91** [comment]
Hi Stefano,
instead of opening a new issue I am replying here to talk about CORS. I have enable with success CORS on a resource of my API with API Gateway. If I test the endpoint with postman it works correctly and I receive the JSON response:

![immagine](https://user-images.githubusercontent.com/12275263/53179412-eeb9f480-35f3-11e9-8ba1-d95100579d8e.png)

but if I want to test CORS on https://www.test-cors.org/ I don't receive response:

![immagine](https://user-images.githubusercontent.com/12275263/53178560-57a06d00-35f2-11e9-9c07-547a580d2ab2.png)

You can see an example that works here:
https://www.test-cors.org/#?client_method=GET&client_credentials=false&client_headers=api_key%3A%20special-key&server_url=https%3A%2F%2Fpetstore.swagger.io%2Fv2%2Fstore%2Finventory&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote

Obviously I have the integration with a Lambda function and lambda integration proxy enabled. 

![immagine](https://user-images.githubusercontent.com/12275263/53179769-abac5100-35f4-11e9-836c-b5e38c8d2488.png)

With the latter I can't set up integration response with proper headers by I trust API Gateway did it when I enabled  CORS (all the processes completed with success). Have you had a chance to test CORS with test-cors.org? I tryed to follow also this guide https://enable-cors.org/server_awsapigateway.html without success.

Thanks,
Michele

**Comment by m1ky91** [comment]
Hi,
I figure it out. Since with the lambda integration proxy we can't set up integration response, I had to hard code the response header into the RestController (I am using Spring Boot 2) in the following way:

`HttpHeaders headers = new HttpHeaders();`
`headers.add("X-Requested-With", "*");`
`headers.add("Access-Control-Allow-Origin", "*");`
`headers.add("Access-Control-Allow-Methods", "GET, POST, DELETE, PUT, PATCH, OPTIONS");`
`headers.add("Access-Control-Allow-Headers", "Content-Type,X-Amz-Date,Authorization,X-Api-Key,x-requested-with");`

And the return the object `headers` with the `ResponseEntity` object.
