### ISSUE TITLE
Only mail attribute in claim : Spark container 

### ISSUE THREAD

**Issue by cenxui** [awslabs/aws-serverless-java-container#82]
Try to get the claim attributes like this.

```
        CognitoAuthorizerClaims claims = 
                awsProxyRequest.getRequestContext().getAuthorizer().getClaims();
        String mail = claims.getEmail();
        String username = claims.getUsername();
        String audience = claims.getAudience();
        String expiration = claims.getExpiration();
        String issuedAt = claims.getIssuedAt();
        String issuer = claims.getIssuer();
```

Only mail is not null. Well, the id_token tested in APIGateway returning the right claim data, but it's not available in spark container.

**Comment by SAPessi** [comment]
Hey @cenxui, I have seen this before when you used the normal POJO handler method. The issue is that the Jackson library Lambda uses behind the scenes does not support annotations - in the context object I'm [using annotations to customize the field names](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/model/CognitoAuthorizerClaims.java#L53). 

If you haven't yet, can you try using the Stream handler with your own instance of Jackson - we have an example [here](https://github.com/awslabs/aws-serverless-java-container/blob/master/samples/spring/pet-store/src/main/java/com/amazonaws/serverless/sample/spring/StreamLambdaHandler.java).

**Comment by cenxui** [comment]
Hello, is it possible that the future version will support annotations?

**Comment by SAPessi** [comment]
Unfortunately it is not something the library can control. The lack of annotations support is part of the Lambda runtime, something we cannot control. I'll ping the Lambda team with this feature request.

**Comment by cenxui** [comment]
Thank you for your kindly repply. It seams that only a work arround can solve this issue. But the problem still exists even though we close this issue. Maybe there should be a proper way to help a new user avoid this problem.

**Comment by SAPessi** [comment]
I'll switch the samples to use the Stream handler and the instructions in the README file. I'll keep this open for tracking the changes.

**Comment by SAPessi** [comment]
Updated all samples and added the docs in the wiki
